import json
import asyncio
from typing import Dict, Any, Optional
from ..orchestrator import IncidentOrchestrator
from ..graph.incident_graph import incident_graph
from ..connectors import sentry_parser, github_connector, slack_connector, linear_connector
from ..eval.scenarios import SCENARIOS

orchestrator = IncidentOrchestrator()

# Definition of standard Model Context Protocol Tools
MCP_TOOLS = [
    {
        "name": "investigate_incident",
        "description": "Trigger autonomous incident investigation correlating Sentry error against git commits using local Qwen 2.5 reasoner.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "scenario_id": {
                    "type": "string",
                    "description": "Pre-configured scenario ID (e.g., 'billing-keyerror', 'auth-jwt-drift', 'rds-outage')"
                },
                "repo": {
                    "type": "string",
                    "description": "GitHub repository target in format 'owner/repo'",
                    "default": "acme-corp/billing-service"
                }
            }
        }
    },
    {
        "name": "run_langgraph_incident",
        "description": "Execute the incident investigation through the LangGraph cyclic state machine with conditional routing and safety guards.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "scenario_id": {
                    "type": "string",
                    "description": "Scenario ID to execute through the state graph"
                }
            },
            "required": ["scenario_id"]
        }
    },
    {
        "name": "create_hotfix_pr",
        "description": "Open a Phase 2 surgical hotfix pull request on GitHub for an identified culprit commit.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "repo": {"type": "string", "description": "GitHub repository"},
                "culprit_sha": {"type": "string", "description": "7-character commit SHA to revert or patch"},
                "title": {"type": "string", "description": "PR title"}
            },
            "required": ["repo", "culprit_sha"]
        }
    }
]


async def handle_tool_call(name: str, arguments: Dict[str, Any]) -> Dict[str, Any]:
    """Execute an MCP tool call and return structured data."""
    if name == "investigate_incident":
        scenario_id = arguments.get("scenario_id", "billing-keyerror")
        scenario = next((s for s in SCENARIOS if s["id"] == scenario_id), SCENARIOS[0])
        res = await orchestrator.run_pipeline(
            alert_payload=scenario["alert"],
            commits=scenario["commits"],
            repo=arguments.get("repo", "acme-corp/billing-service")
        )
        return res.model_dump()

    elif name == "run_langgraph_incident":
        scenario_id = arguments.get("scenario_id", "billing-keyerror")
        scenario = next((s for s in SCENARIOS if s["id"] == scenario_id), SCENARIOS[0])
        initial_state = {
            "alert_payload": scenario["alert"].model_dump() if hasattr(scenario["alert"], "model_dump") else scenario["alert"],
            "repo": "acme-corp/billing-service",
            "alert": None,
            "commits": [c.model_dump() if hasattr(c, "model_dump") else c for c in scenario.get("commits", [])],
            "candidates": [],
            "hypothesis": None,
            "slack_result": None,
            "linear_result": None,
            "hotfix_result": None,
            "status": "started",
            "error": None
        }
        final_state = await incident_graph.ainvoke(initial_state)
        return final_state

    elif name == "create_hotfix_pr":
        repo = arguments["repo"]
        sha = arguments["culprit_sha"]
        title = arguments.get("title", f"fix(revert): auto-revert culprit commit {sha}")
        pr = await github_connector.create_hotfix_pr(
            repo=repo,
            title=title,
            branch_name=f"hotfix/revert-{sha}",
            patch_diff=f"Reverting commit {sha} due to production incident",
            body=f"Automated Hotfix PR generated by Incident Commander Agent for culprit {sha}."
        )
        return pr.model_dump()

    else:
        raise ValueError(f"Unknown MCP tool: {name}")


if __name__ == "__main__":
    import sys
    print(json.dumps({"mcp_version": "1.0", "tools": MCP_TOOLS}, indent=2))
